[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/imageProxy"
  status = 200
  force = true

[functions]
  node_bundler = "esbuild"
  included_files = []

[functions.imageProxy]
  memory = 1024
  maxDuration = 10

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

[build.processing]
  skip_processing = false

[build.processing.images]
  compress = true
