[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/imageProxy"
  status = 200
  force = true

[functions]
  node_bundler = "esbuild"

# Thêm cấu hình cache
[[plugins]]
package = "@netlify/plugin-functions-core"

[plugins.inputs]
  cache_by = "pathname"
  ignore_query = true

# Các header cho caching
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
